# Generated by Django 3.1.3 on 2020-12-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='registration_requested',
        ),
        migrations.AddField(
            model_name='normaluser',
            name='requested_registration',
            field=models.BooleanField(default=True),
        ),
    ]
