# Generated by Django 3.1.3 on 2020-12-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userBase', '0002_normaluser_margin_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='margin_available',
        ),
    ]
