# Generated by Django 3.1.3 on 2020-11-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBase', '0002_normaluser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='normaluser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
