# Generated by Django 3.1.3 on 2020-11-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userBase', '0003_auto_20201118_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='user',
        ),
    ]
