# Generated by Django 3.1.3 on 2020-12-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userBase', '0004_auto_20201225_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normaluser',
            old_name='reference_3_mobile',
            new_name='reference_2_mobile',
        ),
    ]
