# Generated by Django 3.1.3 on 2020-11-21 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userBase', '0004_remove_normaluser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
