# Generated by Django 3.1.3 on 2020-11-18 05:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendorbase', '0001_initial'),
        ('userBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(max_length=200)),
                ('type', models.CharField(choices=[('MARKET', 'MARKET'), ('LIMIT', 'LIMIT')], default='MARKET', max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('EXECUTED', 'EXECUTED'), ('CLOSED', 'CLOSED'), ('CANCELLED', 'CANCELLED')], default='OPEN', max_length=100)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=200)),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendorbase.symbol')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userBase.normaluser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClosedOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderManagement.order',),
        ),
        migrations.CreateModel(
            name='ExecutedOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderManagement.order',),
        ),
        migrations.CreateModel(
            name='OpenOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderManagement.order',),
        ),
    ]
