# Generated by Django 3.1.3 on 2020-12-07 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendorbase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendorbase.symbol'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClosedOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderManagement.order',),
        ),
        migrations.CreateModel(
            name='ExecutedOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderManagement.order',),
        ),
        migrations.CreateModel(
            name='LimitOrderPending',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderManagement.order',),
        ),
        migrations.CreateModel(
            name='OpenOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderManagement.order',),
        ),
    ]
