<<<<<<< HEAD:orderManagement/migrations/0002_auto_20201226_2039.py
# Generated by Django 3.1.3 on 2020-12-26 15:09
=======
# Generated by Django 3.1.3 on 2020-12-26 10:59
>>>>>>> e2e1f8b2f6268c56631f290a94f4bfc6dc8150e0:orderManagement/migrations/0002_auto_20201226_1059.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:orderManagement/migrations/0002_auto_20201226_2039.py
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderManagement', '0001_initial'),
=======
        ('orderManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> e2e1f8b2f6268c56631f290a94f4bfc6dc8150e0:orderManagement/migrations/0002_auto_20201226_1059.py
        ('vendorbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendorbase.symbol'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClosedOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderManagement.order',),
        ),
        migrations.CreateModel(
            name='ExecutedOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderManagement.order',),
        ),
        migrations.CreateModel(
            name='LimitOrderPending',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderManagement.order',),
        ),
        migrations.CreateModel(
            name='OpenOrder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orderManagement.order',),
        ),
    ]
