# Generated by Django 3.1.3 on 2020-12-21 18:52

from django.db import migrations, models
import orderManagement.utils


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0002_auto_20201220_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default=orderManagement.utils.unique_transaction_id_generator, editable=False, max_length=120),
        ),
    ]
