# Generated by Django 3.1.3 on 2020-12-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbase', '0001_initial'),
        ('orderManagement', '0002_auto_20201226_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='instrument_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendorbase.symbol'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('EXECUTED', 'EXECUTED'), ('CLOSED', 'CLOSED'), ('CANCELLED', 'CANCELLED'), ('WAITING_FOR_LIMIT', 'WAITING FOR LIMIT'), ('BEST_LIMIT', 'BEST LIMIT')], default='OPEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('MARKET', 'MARKET'), ('LIMIT', 'LIMIT'), ('BEST_LIMIT', 'BEST LIMIT')], default='MARKET', max_length=200),
        ),
    ]
