# Generated by Django 3.1.3 on 2020-12-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0003_auto_20201228_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='best_limit_id',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
    ]
