# Generated by Django 3.1.3 on 2020-12-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0004_order_best_limit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='best_limit_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=120),
        ),
    ]
