# Generated by Django 3.1.3 on 2020-12-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0005_auto_20201231_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='best_limit_id',
            field=models.CharField(editable=False, max_length=120),
        ),
    ]
