# Generated by Django 3.1.3 on 2020-12-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('contact_details', models.TextField()),
                ('about_us', models.TextField()),
                ('messages', models.TextField()),
                ('delivery_charges', models.TextField()),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendorbase.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
