# Generated by Django 3.1.3 on 2020-12-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendormargin',
            options={'verbose_name': 'User margin', 'verbose_name_plural': 'User margins'},
        ),
        migrations.AddField(
            model_name='vendordetails',
            name='default_margin',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendormargin',
            name='margin_available',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
