# Generated by Django 3.1.3 on 2020-12-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetails',
            name='about_us',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='bank_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='collection_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='delivery_charges',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='gst_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='messages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='mobile_number_1',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='mobile_number_2',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='office_address',
            field=models.TextField(blank=True),
        ),
    ]
