# Generated by Django 3.1.3 on 2020-12-21 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='instrument_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
