# Generated by Django 3.1.3 on 2020-12-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendordetails',
            options={'verbose_name': 'Vendor Details', 'verbose_name_plural': 'Vendor Details'},
        ),
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.CharField(choices=[('Gold 999', 'gold 999'), ('Gold 999 1kg', 'gold 999 1kg'), ('Gold 995', 'gold 995'), ('Gold 995 1kg', 'gold 995 1kg'), ('Gold 999 (T+1)', 'gold 999 t plus 1'), ('Gold 999 1kg (T+1)', 'gold 999 1kg t plus 1'), ('Gold 995 (T+1)', 'gold 995 t plus 1'), ('Gold 995 1kg (T+1)', 'gold 995 1kg t plus 1'), ('Gold 999 (T+2)', 'gold 999 t plus 2'), ('Gold 999 1kg (T+2)', 'gold 999 1kg t plus 2'), ('Gold 995 (T+2)', 'gold 995 t plus 2'), ('Gold 995 1kg (T+2)', 'gold 995 1kg t plus 2')], max_length=500),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='type',
            field=models.CharField(choices=[('Gold 999', 'gold 999'), ('Gold 999 1kg', 'gold 999 1kg'), ('Gold 995', 'gold 995'), ('Gold 995 1kg', 'gold 995 1kg'), ('Silver', 'silver')], default='Gold 999', max_length=200),
        ),
    ]
