# Generated by Django 3.1.3 on 2020-12-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbase', '0002_auto_20201219_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='default_margin',
            field=models.IntegerField(default=500),
        ),
    ]
