# Generated by Django 3.1.3 on 2020-12-06 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendorbase', '0002_auto_20201205_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='vendor',
            name='user_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
