# Generated by Django 3.1.3 on 2020-12-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbase', '0003_vendor_default_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetails',
            name='default_margin',
        ),
    ]
