# Generated by Django 3.1.3 on 2020-12-19 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendorbase', '0001_initial'),
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendorbase.vendor'),
        ),
    ]
