<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-12-26 15:09
=======
# Generated by Django 3.1.3 on 2020-12-26 10:59
>>>>>>> e2e1f8b2f6268c56631f290a94f4bfc6dc8150e0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendorbase', '0001_initial'),
        ('admin_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendorbase.vendor'),
        ),
    ]
