# Generated by Django 3.1.3 on 2020-12-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbase', '0001_initial'),
        ('admin_interface', '0002_theme_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendorbase.vendor'),
        ),
    ]
