# Generated by Django 3.1.3 on 2020-12-09 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_interface', '0003_auto_20201207_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='background_image',
            field=models.FileField(blank=True, help_text='Leave blank to use the default logo', upload_to='logo-assets/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
