# Generated by Django 3.1.3 on 2020-12-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorbase', '0002_auto_20201209_0730'),
        ('admin_interface', '0004_auto_20201209_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background_image',
            field=models.FileField(blank=True, help_text='Leave blank to use the default logo', upload_to='logo-assets/', verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendorbase.vendor'),
        ),
    ]
